import { Prisma } from '@prisma/client'
import { prisma } from '../lib/prisma'
import { calculateOutstandingBalance, calculatePaidAmount, calculateOverdueAmount } from './financial-calculation-service'

export async function getCustomerProfile(id: string) {
  const customer = await prisma.customer.findUnique({ where: { id }, select: { id: true, customerNumber: true, firstName: true, middleName: true, lastName: true, dateOfBirth: true, gender: true, phone: true, alternatePhone: true, email: true, address: true, city: true, region: true, country: true, nationalId: true, occupation: true, employer: true, monthlyIncome: true, status: true, notes: true, createdAt: true, loans: { select: { id: true, loanNumber: true, requestedAmount: true, approvedAmount: true, interestRate: true, status: true, createdAt: true, rolloverFromLoanId: true, rolloverToLoan: { select: { id: true, loanNumber: true, status: true } }, loanType: { select: { name: true } }, repaymentSchedules: { select: { expectedAmount: true, remainingAmount: true, dueDate: true, status: true } }, disbursements: { select: { amount: true, disbursementDate: true } } }, orderBy: { createdAt: 'desc' } }, repayments: { select: { id: true, repaymentNumber: true, amount: true, paymentDate: true, paymentMethod: true, referenceNumber: true, loan: { select: { loanNumber: true } }, recordedBy: { select: { name: true } } }, orderBy: { paymentDate: 'desc' } }, referredCustomers: { select: { id: true, customerNumber: true, firstName: true, middleName: true, lastName: true, phone: true, status: true, loans: { select: { id: true, loanNumber: true, requestedAmount: true, approvedAmount: true, status: true, createdAt: true, loanType: { select: { name: true } }, repaymentSchedules: { select: { installmentNumber: true, expectedAmount: true, amountPaid: true, remainingAmount: true, dueDate: true, status: true }, orderBy: { installmentNumber: 'asc' } }, repayments: { select: { id: true, repaymentNumber: true, amount: true, paymentDate: true, paymentMethod: true }, orderBy: { paymentDate: 'desc' } }, disbursements: { select: { amount: true } } }, orderBy: { createdAt: 'desc' } } }, orderBy: { createdAt: 'desc' } } } })
  if (!customer) return null
  const loanIds = customer.loans.map((loan) => loan.id)
  const repaymentIds = customer.repayments.map((repayment) => repayment.id)
  const activity = await prisma.auditLog.findMany({ where: { OR: [{ entity: 'Customer', entityId: id }, { entity: 'Loan', entityId: { in: loanIds } }, { entity: 'Repayment', entityId: { in: repaymentIds } }] }, include: { user: { select: { name: true } } }, orderBy: { createdAt: 'desc' }, take: 30 })
  const totalBorrowed = customer.loans.reduce((sum, loan) => sum.add(loan.disbursements.reduce((amount, item) => amount.add(item.amount), new Prisma.Decimal(0))), new Prisma.Decimal(0))
  const totalRepaid = calculatePaidAmount(customer.repayments)
  const outstanding = customer.loans.reduce((sum, loan) => sum.add(calculateOutstandingBalance(loan.repaymentSchedules)), new Prisma.Decimal(0))
  const overdue = customer.loans.reduce((sum, loan) => sum.add(calculateOverdueAmount(loan.repaymentSchedules)), new Prisma.Decimal(0))
  return { customer: { ...customer, monthlyIncome: customer.monthlyIncome?.toFixed(2) ?? null }, summary: { totalBorrowed: totalBorrowed.toFixed(2), totalRepaid: totalRepaid.toFixed(2), outstandingBalance: outstanding.toFixed(2), overdueAmount: overdue.toFixed(2), activeLoans: customer.loans.filter((loan) => ['DISBURSED', 'ACTIVE'].includes(loan.status)).length, completedLoans: customer.loans.filter((loan) => loan.status === 'COMPLETED').length }, loans: customer.loans.map((loan) => ({ ...loan, requestedAmount: loan.requestedAmount.toFixed(2), approvedAmount: loan.approvedAmount?.toFixed(2) ?? null, interestRate: loan.interestRate.toFixed(2), schedules: loan.repaymentSchedules.length, disbursed: loan.disbursements.reduce((sum, item) => sum.add(item.amount), new Prisma.Decimal(0)).toFixed(2), outstanding: calculateOutstandingBalance(loan.repaymentSchedules).toFixed(2) })), repayments: customer.repayments.map((repayment) => ({ ...repayment, amount: repayment.amount.toFixed(2) })), referredCustomers: customer.referredCustomers.map((referredCustomer) => ({ ...referredCustomer, name: [referredCustomer.firstName, referredCustomer.middleName, referredCustomer.lastName].filter(Boolean).join(' '), loans: referredCustomer.loans.map((loan) => ({ id: loan.id, loanNumber: loan.loanNumber, loanType: loan.loanType.name, requestedAmount: loan.requestedAmount.toFixed(2), approvedAmount: loan.approvedAmount?.toFixed(2) ?? null, disbursed: loan.disbursements.reduce((sum, item) => sum.add(item.amount), new Prisma.Decimal(0)).toFixed(2), outstanding: calculateOutstandingBalance(loan.repaymentSchedules).toFixed(2), status: loan.status, createdAt: loan.createdAt.toISOString(), schedules: loan.repaymentSchedules.map((schedule) => ({ ...schedule, expectedAmount: schedule.expectedAmount.toFixed(2), amountPaid: schedule.amountPaid.toFixed(2), remainingAmount: schedule.remainingAmount.toFixed(2), dueDate: schedule.dueDate.toISOString() })), repayments: loan.repayments.map((repayment) => ({ ...repayment, amount: repayment.amount.toFixed(2), paymentDate: repayment.paymentDate.toISOString() })) })) })), activity: activity.map((item) => ({ action: item.action.replaceAll('_', ' '), description: item.description, admin: item.user.name, createdAt: item.createdAt.toISOString() })) }
}
