import { Prisma } from '@prisma/client'
import { prisma } from '../lib/prisma'
import { calculateOutstandingBalance, calculatePaidAmount, calculateOverdueAmount } from './financial-calculation-service'

export async function getCustomerProfile(id: string) {
  const customer = await prisma.customer.findUnique({ where: { id }, select: { id: true, customerNumber: true, firstName: true, middleName: true, lastName: true, dateOfBirth: true, gender: true, phone: true, alternatePhone: true, email: true, address: true, city: true, region: true, country: true, nationalId: true, occupation: true, employer: true, monthlyIncome: true, status: true, notes: true, createdAt: true, loans: { select: { id: true, loanNumber: true, requestedAmount: true, approvedAmount: true, interestRate: true, status: true, createdAt: true, loanType: { select: { name: true } }, repaymentSchedules: { select: { expectedAmount: true, remainingAmount: true, dueDate: true, status: true } }, disbursements: { select: { amount: true, disbursementDate: true } } }, orderBy: { createdAt: 'desc' } }, repayments: { select: { id: true, repaymentNumber: true, amount: true, paymentDate: true, paymentMethod: true, referenceNumber: true, loan: { select: { loanNumber: true } }, recordedBy: { select: { name: true } } }, orderBy: { paymentDate: 'desc' } } } })
  if (!customer) return null
  const referredLoans = await prisma.loan.findMany({ where: { referredByCustomerId: id }, select: { id: true, loanNumber: true, requestedAmount: true, status: true, createdAt: true, customer: { select: { firstName: true, middleName: true, lastName: true, customerNumber: true } }, loanType: { select: { name: true } }, repayments: { select: { id: true, repaymentNumber: true, amount: true, paymentMethod: true, paymentDate: true, recordedBy: { select: { name: true } } }, orderBy: { paymentDate: 'desc' } }, repaymentSchedules: { select: { remainingAmount: true } }, disbursements: { select: { amount: true } } }, orderBy: { createdAt: 'desc' } })
  const referredLoanIds = referredLoans.map((loan) => loan.id)
  const loanIds = customer.loans.map((loan) => loan.id)
  const repaymentIds = customer.repayments.map((repayment) => repayment.id)
  const activity = await prisma.auditLog.findMany({ where: { OR: [{ entity: 'Customer', entityId: id }, { entity: 'Loan', entityId: { in: [...loanIds, ...referredLoanIds] } }, { entity: 'Repayment', entityId: { in: repaymentIds } }] }, include: { user: { select: { name: true } } }, orderBy: { createdAt: 'desc' }, take: 30 })
  const totalBorrowed = customer.loans.reduce((sum, loan) => sum.add(loan.disbursements.reduce((amount, item) => amount.add(item.amount), new Prisma.Decimal(0))), new Prisma.Decimal(0))
  const totalRepaid = calculatePaidAmount(customer.repayments)
  const outstanding = customer.loans.reduce((sum, loan) => sum.add(calculateOutstandingBalance(loan.repaymentSchedules)), new Prisma.Decimal(0))
  const overdue = customer.loans.reduce((sum, loan) => sum.add(calculateOverdueAmount(loan.repaymentSchedules)), new Prisma.Decimal(0))
  return { customer: { ...customer, monthlyIncome: customer.monthlyIncome?.toFixed(2) ?? null }, summary: { totalBorrowed: totalBorrowed.toFixed(2), totalRepaid: totalRepaid.toFixed(2), outstandingBalance: outstanding.toFixed(2), overdueAmount: overdue.toFixed(2), activeLoans: customer.loans.filter((loan) => ['DISBURSED', 'ACTIVE'].includes(loan.status)).length, completedLoans: customer.loans.filter((loan) => loan.status === 'COMPLETED').length }, loans: customer.loans.map((loan) => ({ ...loan, requestedAmount: loan.requestedAmount.toFixed(2), approvedAmount: loan.approvedAmount?.toFixed(2) ?? null, interestRate: loan.interestRate.toFixed(2), schedules: loan.repaymentSchedules.length, disbursed: loan.disbursements.reduce((sum, item) => sum.add(item.amount), new Prisma.Decimal(0)).toFixed(2) })), referredLoans: referredLoans.map((loan) => ({ id: loan.id, loanNumber: loan.loanNumber, customer: { name: [loan.customer.firstName, loan.customer.middleName, loan.customer.lastName].filter(Boolean).join(' '), customerNumber: loan.customer.customerNumber }, loanType: loan.loanType.name, requestedAmount: loan.requestedAmount.toFixed(2), disbursed: loan.disbursements.reduce((sum, item) => sum.add(item.amount), new Prisma.Decimal(0)).toFixed(2), outstanding: loan.repaymentSchedules.reduce((sum, item) => sum.add(item.remainingAmount), new Prisma.Decimal(0)).toFixed(2), status: loan.status, createdAt: loan.createdAt.toISOString(), repayments: loan.repayments.map((repayment) => ({ ...repayment, amount: repayment.amount.toFixed(2), paymentDate: repayment.paymentDate.toISOString() })) })), repayments: customer.repayments.map((repayment) => ({ ...repayment, amount: repayment.amount.toFixed(2) })), activity: activity.map((item) => ({ action: item.action.replaceAll('_', ' '), description: item.description, admin: item.user.name, createdAt: item.createdAt.toISOString() })) }
}
